run_logged $TACHARCHY_INSTALL/config/config.sh
run_logged $TACHARCHY_INSTALL/config/branding.sh
run_logged $TACHARCHY_INSTALL/config/tacharchy-detect.sh
run_logged $TACHARCHY_INSTALL/config/git.sh
run_logged $TACHARCHY_INSTALL/config/docker.sh
run_logged $TACHARCHY_INSTALL/config/detect-keyboard-layout.sh
run_logged $TACHARCHY_INSTALL/config/fast-shutdown.sh
run_logged $TACHARCHY_INSTALL/config/hardware/network.sh
run_logged $TACHARCHY_INSTALL/config/hardware/set-wireless-regdom.sh
run_logged $TACHARCHY_INSTALL/config/hardware/fix-fkeys.sh
run_logged $TACHARCHY_INSTALL/config/hardware/bluetooth.sh
run_logged $TACHARCHY_INSTALL/config/hardware/printer.sh
run_logged $TACHARCHY_INSTALL/config/hardware/usb-autosuspend.sh
run_logged $TACHARCHY_INSTALL/config/hardware/nvidia.sh
run_logged $TACHARCHY_INSTALL/config/hardware/intel.sh
run_logged $TACHARCHY_INSTALL/config/hardware/fix-intel-panther-lake-display.sh
run_logged $TACHARCHY_INSTALL/config/hardware/fix-f13-amd-audio-input.sh
run_logged $TACHARCHY_INSTALL/config/hardware/fix-bcm43xx.sh
run_logged $TACHARCHY_INSTALL/config/hardware/fix-apple-spi-keyboard.sh
run_logged $TACHARCHY_INSTALL/config/hardware/fix-apple-suspend-nvme.sh
run_logged $TACHARCHY_INSTALL/config/hardware/fix-apple-t2.sh
run_logged $TACHARCHY_INSTALL/config/hardware/fix-surface-keyboard.sh
run_logged $TACHARCHY_INSTALL/config/hardware/fix-asus-rog-audio-mixer.sh
run_logged $TACHARCHY_INSTALL/config/hardware/fix-asus-rog-mic.sh
run_logged $TACHARCHY_INSTALL/config/hardware/fix-yt6801-ethernet-adapter.sh
run_logged $TACHARCHY_INSTALL/config/hardware/fix-synaptic-touchpad.sh
run_logged $TACHARCHY_INSTALL/config/hardware/framework16-qmk-hid.sh
